module.exports = {
  NODE_ENV: '"production"',

  FIRMWARES_API_ENDPOINT:     process.env.FIRMWARES_API_ENDPOINT,
  SERVER_SETUP_API_ENDPOINT:  process.env.SERVER_SETUP_API_ENDPOINT,
  STATS_API_ENDPOINT:         process.env.STATS_API_ENDPOINT,
  BTC_WALLET_ADDRESS:         process.env.BTC_WALLET_ADDRESS
}
